---
abstract: 'Wrapper for the Handlebars template system'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  Dancer: '0'
  Dancer::Test: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::More: '0.88'
  lib: '0'
  parent: '0'
  perl: '5.006'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Template-Handlebars
provides:
  Dancer::Template::Handlebars:
    file: lib/Dancer/Template/Handlebars.pm
    version: v0.1.0
  Dancer::Template::Handlebars::Helpers:
    file: lib/Dancer/Template/Handlebars/Helpers.pm
    version: v0.1.0
requires:
  Dancer::Config: '0'
  Dancer::Template::Abstract: '0'
  Moo: '0'
  Sub::Attribute: '0'
  Text::Handlebars: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dancer-Template-Handlebars/issues
  homepage: http://search.cpan.org/dist/Dancer-Template-Handlebars/
  repository: https://github.com/yanick/Dancer-Template-Handlebars.git
version: 0.1.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Yanick Champoux <yanick@cpan.org>'
